Use bash script wrapper for julietflow

diff --git a/scripts/minorvariant/julietflow b/scripts/minorvariant/julietflow
--- a/scripts/minorvariant/julietflow
+++ b/scripts/minorvariant/julietflow
@@ -1,38 +1,104 @@
 #!/usr/bin/env bash
-set -euo pipefail
-if [[ $1 == /* ]]; then input=$1; else input=$(pwd)/$1; fi
-if [[ $2 == /* ]]; then reference=$2; else reference=$(pwd)/$2; fi
-reference=$2
-cores=8
-max=1
-ref_map=$reference
-if [ $# -ge 3 ]; then cores=$3; fi
-if [ $# -ge 4 ]; then max=$4; fi
-if [ $# -ge 5 ]; then ref_map=$5; fi
+#
+# ##########
+# JULIETFLOW
+# ##########
+#
+# Exit on error. Append "|| true" if you expect an error.
+set -o errexit
+# Exit on error inside any functions or subshells.
+set -o errtrace
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
 
+function echoHelp() {
+    echo "  -i [arg]  BAM CCS file to process. Required.
+  -r [arg]  Reference FASTA file. Required.
+  -c [arg]  Juliet target config. Default='<HIV>'
+  -j [arg]  Number of CPU cores. Default=1
+  -m [arg]  Maximal number of re-align iterations. Default=1
+  -t [arg]  Target reference FASTA, per default using --ref.
+  -k        Keep temporary files
+  -h        This help page"
+  exit 0
+}
+
+# Option parsing
+config='<HIV>'
+cores=1
+max=1
+keep="0"
+helpRequested="0"
+
+if [[ $# -eq 0 ]]; then
+    echoHelp
+fi
+
+while getopts ":h :i: :r: :c: :j: :t: :k :m:" opt; do
+  case $opt in
+    i)
+      if [[ ${OPTARG} == /* ]]; then input=${OPTARG}; else input=$(pwd)/${OPTARG}; fi;;
+    r)
+      if [[ ${OPTARG} == /* ]]; then reference=${OPTARG}; else reference=$(pwd)/${OPTARG}; fi;;
+    c)
+      config=$OPTARG;;
+    j)
+      cores=$OPTARG;;
+    t)
+      target=$OPTARG;;
+    m)
+      max=$OPTARG;;
+    k)
+      keep="1";;
+    h)
+      helpRequested="1"
+      echo "get help";;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2;;
+  esac
+done
+
+if [[ -z "${input:-}" ]]; then
+    echo "Please provide the CCS BAM file via -i"
+    exit 1
+fi
+
+if [[ -z "${reference:-}" ]]; then
+    echo "Please provide the reference FASTA file via -r"
+    exit 1
+fi
+
+if [[ "${helpRequested}" = "1" ]]; then
+  echoHelp
+fi
+
+if [[ -z "${target:-}" ]]; then
+  target=$reference
+fi
+
+# Get directory of the input file, file prefix and suffix
 run_directory=${input%/*}
 run_name=${input##*/}
 run_suffix=${run_name##*.}
 run_prefix=${run_name%.*}
 
-function blasrAlign()
-{
-    blasr $input $1 --placeGapConsistently --bam --out out.bam --nproc ${cores} --scoreMatrix "-1 4 4 4 6 4 -1 4 4 6 4 4 -1 4 6 4 4 4 -1 6 6 6 6 6 6" --maxMatch 15 &>> console
-    samtools sort -@${cores} -o ${run_prefix}.align.bam out.bam 2>> console
-    samtools index ${run_prefix}.align.bam &>> console
-    rm out.bam
-}
-function bwaAlign()
-{
-    samtools view $input | awk '{print ">"$1"\n"$10 }' > data.fasta
-    cp $1 ref.fasta
-    if [ ! -f ref.fasta.bwt ]; then bwa index ref.fasta &>> console; fi
-    bwa mem -t ${cores} ref.fasta data.fasta 2>> console | sed 's/M/=/g' | samtools view -F 0x800 -bS - 2>> console | samtools sort -@${cores} -o ${run_prefix}.align.bam 2>> console
-    samtools index ${run_prefix}.align.bam &>> console
-}
+# Main script
+wdir=$(pwd)
+if [[ "${keep}" = "1" ]]; then
+  if [[ -d ${wdir}/tmp ]]; then
+    echo "Directory ${wdir}/tmp already exists, please remove to use option -k"
+    exit 1
+  fi
+fi
+
 function align()
 {
-    blasrAlign $@;
+    blasr ${input} $1 --placeGapConsistently --bam --out out.bam --nproc ${cores} --scoreMatrix "-1 4 4 4 6 4 -1 4 4 6 4 4 -1 4 6 4 4 4 -1 6 6 6 6 6 6" --maxMatch 15
+    samtools sort -@${cores} -o ${run_prefix}.align.bam out.bam
+    samtools index ${run_prefix}.align.bam
+    rm out.bam
 }
 
 # Create provided directory tree and cd
@@ -43,31 +109,35 @@ function mmkdir()
 }
 
 # Create temporary directory, under which all work will be performed
-wdir=`pwd`
-tdir=`mktemp -d` && cd $tdir
-#echo $tdir
+tdir=$(mktemp -d) && cd ${tdir}
 
 # Generally, never do work if file is already present.
 # Align against given reference and create consensus sequence
 mmkdir 0
-if [ ! -f $run_prefix.align.bam ]; then align $reference; fi
-if [ ! -f $run_prefix.cons ]; then cp $reference $run_prefix.cons; fi
+if [ ! -f ${run_prefix}.align.bam ]; then align ${reference}; fi
+if [ ! -f ${run_prefix}.cons ]; then cp ${reference} ${run_prefix}.cons; fi
 cd ..
 
 # Iteratively align against previous consensus
-for i in $(seq 1 $max); do
+for i in $(seq 1 ${max}); do
     mmkdir ${i}
-    if [ ! -f $run_prefix.cons ]; then fuse ../$(($i-1))/$run_prefix.align.bam; fi
-    if [ ! -f $run_prefix.align.bam ]; then align $run_prefix.cons; fi
+    if [ ! -f ${run_prefix}.cons ]; then fuse ../$(($i-1))/${run_prefix}.align.bam; fi
+    if [ ! -f ${run_prefix}.align.bam ]; then align ${run_prefix}.cons; fi
     cd ..
 done
 
 # Re-map last alignment against original reference
 mmkdir merge
-cleric ../${max}/$run_prefix.align.bam ../${max}/$run_prefix.cons $ref_map
-juliet ${run_prefix}_cleric.bam -c '<HIV>'
-cp ${run_prefix}_cleric.html $wdir/
+cleric ../${max}/${run_prefix}.align.bam ../${max}/${run_prefix}.cons $target
+juliet ${run_prefix}_cleric.bam -c ${config}
+cp ${run_prefix}_cleric.html ${wdir}/
+
+if [[ "${keep}" = "1" ]]; then
+  mkdir ${wdir}/tmp
+  cd ..
+  cp -R * ${wdir}/tmp/
+fi
 
 # switch back to original root
-cd $wdir
-rm -rf $tdir
+cd ${wdir}
+rm -rf ${tdir}
